name: this-sorta-doesnt-work
favicon: null
layout_spectrum: 0.36947759590111673
typography_spectrum: 0.8762625858653337
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9111567167565227
  lightness: 0.2407937932293862
  saturation: 0.5806277554947883
  rhythmicContrast: 0.7790122572332621
purpose: []
